# Generated by Django 2.2.2 on 2019-06-30 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens', models.CharField(max_length=1000)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_org', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=36)),
                ('title', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
                ('user_agrees', models.CharField(max_length=10)),
                ('org_filled', models.BooleanField(default=False)),
                ('time_till', models.DateField()),
                ('is_verified', models.BooleanField(default=False)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cert_org', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cert_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
