# Generated by Django 2.2.2 on 2019-06-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='org',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
