# Generated by Django 2.2.2 on 2019-06-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_auto_20190630_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
