# Generated by Django 2.2.2 on 2019-06-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_is_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.DeleteModel(
            name='AdFile',
        ),
    ]
